Project Zeus {
  database_type: 'PostgreSQL'
  Note: '''
    # Zeus E-commerce management
  '''
}

Table UserType {
  id          int          [pk, increment, not null]
  description varchar (50) [not null]
  createdAt   timestamp    [not null, default: 'now()']
  updatedAt   timestamp    [not null, default: 'now()']
  deletedAt   timestamp
}

Table User {
  id         varchar (100) [not null, pk]
  name       varchar (50)  [not null]
  username   varchar (50)  [not null]
  password   varchar (150) [not null]
  userTypeId int           [not null]
  token      varchar (150)
  createdAt  timestamp     [not null, default: 'now()']
  updatedAt  timestamp     [not null, default: 'now()']
  deletedAt  timestamp
}

Table Permission {
  id          int          [pk, increment, not null]
  description varchar (50) [not null]
  createdAt   timestamp    [not null, default: 'now()']
  updatedAt   timestamp    [not null, default: 'now()']
  deletedAt   timestamp
}

Table Module {
  id          int          [pk, increment, not null]
  description varchar (50) [not null]
  createdAt   timestamp    [not null, default: 'now()']
  updatedAt   timestamp    [not null, default: 'now()']
  deletedAt   timestamp
}

Table PermissionGroup {
  id           int       [pk, increment, not null]
  userTypeId   int       [not null]
  permissionId int       [not null]
  moduleId     int       [not null]
  status       boolean   [not null, default: true]
  createdAt    timestamp [not null, default: 'now()']
  updatedAt    timestamp [not null, default: 'now()']
  deletedAt    timestamp
}

Table Company {
  id             varchar       [pk, not null]
  name           varchar (50)  [not null]
  displayName    varchar (50)  [not null]
  email          varchar (100) [not null]
  status         boolean       [not null, default: true]
  createdAt      timestamp     [not null, default: 'now()']
  updatedAt      timestamp     [not null, default: 'now()']
  deletedAt      timestamp
}

Table UserCompany {
  id        int       [pk, increment, not null]
  userId    int       [not null]
  companyId int       [not null]
  deletedAt timestamp
}

Table ServicePack {
  id                varchar           [pk, not null]
  name              varchar   (50)    [not null]
  description       varchar   (100)   [not null]
  duration          int               [not null, default: 12, Note: 'in months']
  subscriptionPrice decimal   (10, 4) [not null]
  monthlyPayment    decimal   (10, 4) [not null]
  lateFee           decimal   (10, 4) [not null]
  monthlyFee        decimal   (10, 5) [not null]
  status            boolean           [not null, default: true]
  coinId            int               [not null, Note: 'Defines the main coin to make conversion to others, if needed']
  createdAt         timestamp         [not null, default: 'now()']
  updatedAt         timestamp         [not null, default: 'now()']
  deletedAt         timestamp
}

Table ServicePackItemType {
  id             int            [pk, increment, not null]
  description    varchar   (50) [not null]
  createdAt      timestamp      [not null, default: 'now()']
  updatedAt      timestamp      [not null, default: 'now()']
}

Table ServicePackItem {
  id             varchar        [pk, not null]
  itemTypeId     int            [not null]
  servicePackId  varchar        [not null]
  amount         int            [not null]
  status         boolean        [not null, default: true]
  createdAt      timestamp      [not null, default: 'now()']
  updatedAt      timestamp      [not null, default: 'now()']
  deletedAt      timestamp
}

Table Contract {
  id                varchar           [pk, not null]
  servicePackId     varchar           [not null]
  companyId         varchar           [not null]
  clientId          varchar           [not null]
  subscriptionPrice decimal   (10, 4) [not null]
  monthlyPayment    decimal   (10, 4) [not null]
  lateFee           decimal   (10, 4) [not null]
  monthlyFee        decimal   (10, 5) [not null]
  expiresAt         date              [not null]
  coinId            int               [not null]
  status            boolean           [not null, default: true]
  createdAt         timestamp         [not null, default: 'now()']
  updatedAt         timestamp         [not null, default: 'now()']
  deletedAt         timestamp
}

Table PaymentMethod {
  id          int          [pk, increment, not null]
  description varchar (50) [not null]
  status      boolean      [not null, default: true]
  createdAt   timestamp    [not null, default: 'now()']
  updatedAt   timestamp    [not null, default: 'now()']
  deletedAt   timestamp

  note: 'Credit Card, Boleto, Cash, ...'
}

Table InstallmentType {
  id          int          [pk, increment, not null]
  description varchar (50) [not null]
  status      boolean      [not null, default: true]
  createdAt   timestamp    [not null, default: 'now()']
  updatedAt   timestamp    [not null, default: 'now()']
  deletedAt   timestamp

  note: 'Subscription, Monthly Payment, Annual Payment'
}

Table Coin {
  id          int             [pk, increment, not null]
  name        varchar (50)    [not null]
  acronym     varchar (3)     [not null]
  value       decimal (10, 4) [not null, Note: 'Uses USD as base']
  status      boolean         [not null, default: true]
  createdAt   timestamp       [not null, default: 'now()']
  updatedAt   timestamp       [not null, default: 'now()']
  deletedAt   timestamp
}

Table Installment {
  id                varchar           [pk, not null]
  contractId        varchar           [not null]
  installmentTypeId int               [not null]
  paymentMethodId   int               [not null]
  coinId            int               [not null]
  value             decimal   (10, 4) [not null]
  valuePaid         decimal   (10, 4) [not null]
  expiresAt         datetime          [not null]
  paidAt            timestamp         [not null]
  createdAt         timestamp         [not null, default: 'now()']
  updatedAt         timestamp         [not null, default: 'now()']
  deletedAt         timestamp
}

Table Client {
  id        varchar         [pk, not null]
  name      varchar   (50)  [not null]
  email     varchar   (100) [not null]
  createdAt timestamp       [not null, default: 'now()']
  updatedAt timestamp       [not null, default: 'now()']
  deletedAt timestamp
}

Table ServiceStage {
  id          int          [pk, increment, not null]
  description varchar (50) [not null]
  status      boolean      [not null, default: true]
  createdAt   timestamp    [not null, default: 'now()']
  updatedAt   timestamp    [not null, default: 'now()']
  deletedAt   timestamp

  note: 'Waiting for service, in attendance, refused services, accepted services, ...'
}

Table CostumerService {
  id             int       [pk, increment, not null]
  clientId       varchar   [not null]
  userId         varchar   [not null]
  serviceStageId int       [not null]
  createdAt      timestamp [not null, default: 'now()']
  updatedAt      timestamp [not null, default: 'now()']
  deletedAt      timestamp
}

Table ClientBlackListReason {
  id          int            [pk, increment, not null]
  title       varchar   (50) [not null]
  details     text           [not null]
  createdAt   timestamp      [not null, default: 'now()']
  updatedAt   timestamp      [not null, default: 'now()']
  deletedAt   timestamp
}

Table ClientBlackList {
  id                      int       [pk, increment, not null]
  clientId                varchar   [not null]
  clientBlackListReasonId int       [not null]
  createdAt               timestamp [not null, default: 'now()']
  updatedAt               timestamp [not null, default: 'now()']
  deletedAt               timestamp
}

Table SupportTicket {
  id        varchar        [pk, not null]
  clientId  varchar        [not null]
  userId    varchar        [not null]
  reason    varchar   (50) [not null]
  details   text           [not null]
  createdAt timestamp      [not null, default: 'now()']
  updatedAt timestamp      [not null, default: 'now()']
  deletedAt timestamp
}

Ref "User_UserType_fk": User.userTypeId < UserType.id
Ref "PermissionGroup_UserType_fk": PermissionGroup.userTypeId < UserType.id
Ref "PermissionGroup_Permission_fk": PermissionGroup.permissionId < Permission.id
Ref "PermissionGroup_Module_fk": PermissionGroup.moduleId < Module.id
Ref "ServicePackItem_ServicePackItemType_fk": ServicePackItem.itemTypeId < ServicePackItemType.id
Ref "ServicePackItem_ServicePack_fk": ServicePackItem.servicePackId < ServicePack.id
Ref "Contract_ServicePack_fk": Contract.servicePackId < ServicePack.id
Ref "Contract_Company_fk": Contract.companyId < Company.id
Ref "Contract_Client_fk": Contract.clientId < Client.id
Ref "UserCompany_User_fk": UserCompany.userId < User.id
Ref "UserCompany_Company_fk": UserCompany.companyId < Company.id
Ref "Installment_PaymentMethod_fk": Installment.paymentMethodId < PaymentMethod.id
Ref "Installment_InstallmentType_fk": Installment.installmentTypeId < InstallmentType.id
Ref "Installment_Coin_fk": Installment.coinId < Coin.id
Ref "Installment_Contract_fk": Installment.contractId < Contract.id
Ref "CostumerService_Client_fk": CostumerService.clientId < Client.id
Ref "CostumerService_ServiceStage_fk": CostumerService.serviceStageId < ServiceStage.id
Ref "CostumerService_User_fk": CostumerService.userId < User.id
Ref "ClientBlackList_ClientBlackListReason_fk": ClientBlackList.clientBlackListReasonId < ClientBlackListReason.id
Ref "ClientBlackList_Client_fk": ClientBlackList.clientId < Client.id
Ref "SupportTicket_Client_fk": SupportTicket.clientId < Client.id
Ref "SupportTicket_User_fk": SupportTicket.userId < User.id
Ref "ServicePack_Coin_fk": ServicePack.coinId < Coin.id
