version: "3.9"
services:
  app:
    volumes:
      - .:/usr/src/app
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file: .env
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
  db_test:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    env_file: .env.test
  test:
    volumes:
      - .:/usr/src/app
    build: .
    depends_on:
      - db_test
    ports:
      - "3001:3001"
    env_file: .env.test

volumes:
  atena: