name: Unit test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Job executed by ${{ github.actor }} in a ${{ github.event_name }} at ${{ github.ref_name }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install bcrypt
        run: yarn add bcrypt
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test
